/* Generated By:JJTree: Do not edit this line. ASTClassValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassValue extends SimpleNode {
  public ASTClassValue(int id) {
    super(id);
  }

  public ASTClassValue(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Statements jjtAccept(ExpressionParserVisitor visitor, Statements data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=408dedf20b968236ffad7df244ea1b9d (do not edit this line) */
