/* Generated By:JJTree: Do not edit this line. ASTNumberValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNumberValue extends SimpleNode {
  public ASTNumberValue(int id) {
    super(id);
  }

  public ASTNumberValue(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Statements jjtAccept(ExpressionParserVisitor visitor, Statements data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc0a3012d44a68b5b04bac46be7ba16c (do not edit this line) */
