/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 4;
  /** RegularExpression Id. */
  int UPDATE = 5;
  /** RegularExpression Id. */
  int SET = 6;
  /** RegularExpression Id. */
  int LINK = 7;
  /** RegularExpression Id. */
  int TABLE = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int SPACE = 11;
  /** RegularExpression Id. */
  int LEFT_PAREN = 12;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int QUOTE_MARK = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int LETTER = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CREATE>",
    "<UPDATE>",
    "<SET>",
    "<LINK>",
    "<TABLE>",
    "<NUMBER>",
    "<STRING>",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"\\\'\"",
    "<DIGIT>",
    "<LETTER>",
  };

}
